#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: inginx-ing
#  namespace: default
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: ingress-nginx-admission
#spec:
#  rules:
#    - host: 172.27.22.51:3000
#      http:
#        paths:
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: react-js
#                port:
#                  number: 3000
#          - path: /actions
#            pathType: Prefix
#            backend:
#              service:
#                name: action-server
#                port:
#                  number: 5055
#          - path: /rasa
#            pathType: Prefix
#            backend:
#              service:
#                name: rasa
#                port:
#                  number: 5005
#          - path: /data_extraction
#            pathType: Prefix
#            backend:
#              service:
#                name: data-extraction
#                port:
#                  number: 5006
