apiVersion: v1
kind: Service
metadata:
  name: {{ include "rasa.fullname" . }}
  labels:
    {{- include "rasa.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5005
      protocol: TCP
      name: http
  selector:
    {{- include "rasa.selectorLabels" . | nindent 4 }}
